# -*- coding: utf-8 -*-
"""LVADSUSR67_Aishwarya_IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rsGoV13jhnoCfsoiLwYV16vmPhy8v3ql
"""

#1
import numpy as np
import pandas as pd
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],
                    [[255,255,0],[255,0,255],[0,255,255]],
                    [[127,127,127],[200,200,200],[50,50,50]]])

#2
health_data=np.array([[{'Patient 1':[160,54,18],
                      'Patient 2':[168,65,23],
                      'Patient 3':[159,58,20]}]])
norm=np.linalg.norm(health_data[0:3])

#3
data =np.array( [[[{'A':[[13.2, 14.2, 13.5, 13.6, 14.3],[1.2,1.4,1.5,9.7,8.2]]}]]])
data2=np.array([[[{'B':[[10.2,10.4,10.6,10.7,10.8],[6.5,5.4,6.7,6.6,6.5]]}]]])
d3=np.array([data,data2])
d3.flatten()
d3.reshape(1,2)
print(d3)

#4
data={'Player 1':[10,7,8,5,10],
      'Player 2':[5,8,9,10,3],
      'Player 3':[8,9,6,10,8]}

df=pd.DataFrame(data)
df

#7
data={'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
      'Age':[25,30,35,40,45,50,55],
      'City':['NY','LA','Chicago','Houston','Phoenix','Miami','Boston'],
      'Dept':['HR','IT','Finance','Marketing','Sales','IT','HR']}
df=pd.DataFrame(data)
df
filtered=df[(df['Age']<45)&(df['Dept']!='HR')]
df1=filtered[['Name','City']]
df1

#8
data={'Product':['Apple','Banana','Cherry','Dates','ElderBerries','Grapes'],
      'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Fruit'],
      'Price':[1.20,0.50,3.00,2.50,4.00,2.00],
      'Promotion':['True','False','True','True','False','False']
      }
df=pd.DataFrame(data)
df
filtered=df[(df['Price']>2.19) & (df['Promotion']=='False')]
df1=filtered['Product']
df1

#9
data={'Employee':['Alice','Bob','Charlie','David'],
      'Dept':['HR','IT','Finance','IT'],
      'Manager':['John','rachel','emily','rachel']
    }
data1={'Employee':['Alice','Charlie','Eve'],
       'Project':['p1','p3','p2']}
df1=pd.DataFrame(data)
df2=pd.DataFrame(data1)
df=pd.merge(df1,df2,on="Employee",how="outer")
df

#10